// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "dd169642-e530-4676-b5dd-80d478a86697");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1772866060);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1772866058);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{5f58f0e0-fee7-4ec2-b9bc-77c2a03f5c94}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 150);
user_pref("browser.newtabpage.activity-stream.discoverystream.spoc-positions", "2,4,8,13,17,20");
user_pref("browser.newtabpage.activity-stream.impressionId", "{b65f41d2-918b-4c6a-a834-5cf21717b06a}");
user_pref("browser.newtabpage.activity-stream.unifiedAds.spocs.enabled", true);
user_pref("browser.newtabpage.activity-stream.unifiedAds.tiles.enabled", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1772866053);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1772866060015");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1772887660015");
user_pref("browser.search.region", "NP");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1772866056");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1772866054);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1772866058);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":21,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("captchadetection.lastSubmission", 1772866);
user_pref("datareporting.dau.cachedUsageProfileID", "3b28ee36-134a-4429-9091-de5472957892");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1772866056895");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "135.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "NP");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "c5d0261d39354756a394bc4097d46d02");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECK7ylndIVDKfBAjzyiPLUAkPDQ==");
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20250211160552");
user_pref("extensions.lastAppVersion", "135.0");
user_pref("extensions.lastPlatformVersion", "135.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"5ada8b30-8d77-46f4-9333-6ca9854bcb56\",\"pictureinpicture@mozilla.org\":\"99d02e86-2755-43c6-a59b-329f14cbcacf\",\"screenshots@mozilla.org\":\"cf36150c-9aa5-4106-b380-bfcd59e49f96\",\"webcompat-reporter@mozilla.org\":\"6206a12a-fd23-4bed-91c7-367bf2c11ee7\",\"webcompat@mozilla.org\":\"d94b8d5d-0cb3-4101-a4af-4e4573a13ff8\",\"default-theme@mozilla.org\":\"eeddf480-fabd-4f96-a998-f1dbba9cc81b\",\"addons-search-detection@mozilla.com\":\"4ca8e565-3f93-41d3-a0cf-592e27f1fa86\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"width\":\"\",\"command\":\"\",\"expanded\":false,\"hidden\":true}");
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECE93DD0VWxJlBAjLZTKIPpskvA==");
user_pref("toolkit.startup.last_success", 1772866050);
user_pref("toolkit.telemetry.cachedClientID", "e844f7de-c9c3-412c-9f92-1b520d552c2c");
user_pref("toolkit.telemetry.cachedProfileGroupID", "b0e20c2f-e687-44b3-8a17-212d1668ebee");
user_pref("toolkit.telemetry.previousBuildID", "20250211160552");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
